services:
  web:
    image: nginx:latest
    ports:
      - 8090:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html
    environment: #para ficar disponivel no app
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: financas
      MYSQL_USER: admin
  db:
    image: mysql:latest
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: financas

volumes:
  mysqldata: